version: '3'

services:
  nginx:
    image: nginx:stable
    container_name: tz-nginx
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
    ports:
      - "1180:80"
    depends_on:
      - fpm


  fpm:
    build: docker/fpm
    container_name: tz-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/fpm/conf.d/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./docker/fpm/conf.d/opcache.ini:/usr/local/etc/php/conf.d/90-opcache.ini
    environment:
      - PHP_IDE_CONFIG='serverName=tz'